#include <tool/error_code.h>

namespace tool
{

const char* const error_message[]
{
	"NO_ERR",
	"CANNOT_ALLOCATE_MEMORY",
	"CANNOT_CREATE_MODULE_SNAPSHOT",
	"CANNOT_CREATE_PROCESS_SNAPSHOT",
	"CANNOT_CREATE_REMOTE_THREAD",
	"CANNOT_GET_CURRENT_DIRECTORY",
	"CANNOT_GET_FUNCTION_ADDRESS",
	"CANNOT_GET_FULL_PATH",
	"CANNOT_GET_MODULE_ADDRESS",
	"CANNOT_GET_PROCESS_ID",
	"CANNOT_OPEN_PROCESS",
	"CANNOT_READ_FROM_PROCESS",
	"CANNOT_WRITE_TO_PROCESS",
	"INVALID_PATH",

	"CANNOT_GET_ADDRESS_INFO",
	"CANNOT_CREATE_SOCKET",
	"CANNOT_CONNECT_TO_SERVER",
	"CANNOT_BIND_SOCKET",
	"CANNOT_LISTEN_TO_SOCKET",
	"CANNOT_ACCEPT_CONNECTION",
	"WSASTARTUP_FAILED",
	"WSACLEANUP_FAILED",
	"CANNOT_CLOSE_SOCKET",
	"CANNOT_READ_SOCKET",
	"CANNOT_WRITE_SOCKET",
	"BUFFER_OUT_OF_RANGE"
};

const char* error_to_string(error_code err) noexcept
{
	return error_message[(int)err];
}

} // namespace